# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # pod 'GoogleMaps', '8.2.0'

end
